sudo: required
dist: trusty
group: edge
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
  hosts:
      - magento2.travis
language: php
matrix:
  include:
    - php: 7.2
      env:
       - MAGENTO_VERSION=2.3
       - TEST_SUITE=integration
    - php: 7.2
      env:
       - MAGENTO_VERSION=2.3-develop
       - TEST_SUITE=integration
    - php: 7.1
      env:
       - MAGENTO_VERSION=2.3-develop
       - TEST_SUITE=integration
    - php: 7.1
      env:
        - MAGENTO_VERSION=2.2-develop
        - TEST_SUITE=integration
    - php: 7.1
      env:
        - MAGENTO_VERSION=2.2.7
        - TEST_SUITE=integration
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - COMPOSER_PACKAGE_NAME=integer-net/magento2-session-unblocker
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
before_script: ./.travis/before_script.sh
script: phpunit -c magento2/dev/tests/$TEST_SUITE --coverage-text --coverage-clover=coverage.clover
after_script:
  - |
    wget https://scrutinizer-ci.com/ocular.phar
    php ocular.phar code-coverage:upload --format=php-clover coverage.clover
